### ISSUE TITLE
Incorrect size of unsized single-bit values

### ISSUE THREAD

**Issue by kbieganski** [chipsalliance/Surelog#1472]
SystemVerilog example:
```systemverilog
module M;
   parameter logic [7:0] P = '0;
endmodule
```
UHDM generated by Surelog:
```
|uhdmtopModules:
\_module: work@M (work@M) /home/krzysztof/verilator-uhdm/uhdm-integration/tests/bug/dut.v:1:1: , endln:3:10
  |vpiDefName:work@M
  |vpiName:work@M
  |vpiParamAssign:
  \_param_assign: , line:2:26, endln:2:32, parent:work@M
    |vpiRhs:
    \_constant: , line:2:30, endln:2:32
      |vpiConstType:9
      |vpiDecompile:0
      |vpiSize:1
      |UINT:0
    |vpiLhs:
    \_parameter: (work@M.P), line:2:26, endln:2:32, parent:work@M
      |vpiName:P
      |vpiFullName:work@M.P
      |BIN:0
      |vpiTypespec:
      ...
```
According to EEE 1800-2017 5.7.1 , the constant assigned to `P` should be resized to `P`'s size, so it should be 8 bits, not 1.

@alaindargelas said in https://github.com/chipsalliance/Surelog/issues/1454#issuecomment-875398312:
> Surelog does not reconcile lhs and rhs expression dimensions at this time. 
> This is left to the client application for now.

Wouldn't it be better for now to indicate that the constant is unsized? (e.g. by removing the `vpiSize` attribute, or having `'0`/`'1`/etc. stored in `vpiDecompile`)
`vpiSize` set to 1 makes it seem like it should be exactly 1 bit long.

**Comment by alaindargelas** [comment]
Fixed by #1421
