### ISSUE TITLE
Surelog elaboration options

### ISSUE THREAD

**Issue by RRozak** [chipsalliance/Surelog#1502]
According to output of `-help` there are 3 elaboration options: `-noelab`, `-elabuhdm` and `Folded Model` which is the default one.
Is there any documentation regarding the differences between them?

**Comment by alaindargelas** [comment]
There is no further documentation than the help.
The one you need is either -elabuhdm pre-saving of UHDM or post-read of UHDM, invoke the UHDM elaboration programmatically.
