### ISSUE TITLE
Important vpiActual nodes only with -elabuhdm flag

### ISSUE THREAD

**Issue by RRozak** [chipsalliance/Surelog#1503]
To have the proper type of `result` variable in https://github.com/chipsalliance/Surelog/issues/1449, the `-elabuhdm` option is required.

Is it intentional?
These nodes are needed in uhdm-verilator, but full elaboration option can include many other nodes that are not needed and may cause performance problems.

**Comment by alaindargelas** [comment]
Yes, it's mandatory. I'm not going to develop an a-la-carte elaboration option. That would be a maintenance nightmare.
Make sure you invoke the elaboration after you load UHDM, not before you save it. That will take care of the performance issues you see.
