### ISSUE TITLE
ModuleInstance::getFileName() looks corrupted

### ISSUE THREAD

**Issue by pieter3d** [chipsalliance/Surelog#1557]
To repro, modify the hellosureworld.cpp by adding the following print after the instance print (line 60 as of 3177342afb6004ec1a416372c4600c065c0a8669):
```c++
std::cout << "File: " << inst->getFileName() << std::endl;
```
The printout from parsing a design shows some of the file name but generally looks pretty corrupted.

**Comment by alaindargelas** [comment]
Fixed by #1560
