### ISSUE TITLE
logic_net includes [net_drivers] and [net_loads] 

### ISSUE THREAD

**Issue by bsp13** [chipsalliance/Surelog#1565]
Currently I did not get any data from [net_drivers] and [net loads]. have any future plan of it?

**Comment by alaindargelas** [comment]
Not at this time.
Surelog does not create a fully connected flattened netlist (which is needed to make that computation).

**Comment by alaindargelas** [comment]
I have no bandwidth to work on this, but I'll help anyone who wants to take a stabb at it.
