### ISSUE TITLE
Make sure Surelog can parse wavious LPDDR4 PHY

### ISSUE THREAD

**Issue by mithro** [chipsalliance/Surelog#1638]
The PHY can be found at https://github.com/waviousllc/wav-lpddr-hw

Seems to be written in SystemVerilog -> https://github.com/waviousllc/wav-lpddr-hw/search?l=systemverilog

> ### Tools Required
> The WDDR UVM testbench has been developed with Cadence VIP and simulators. Users must ensure that the VIP and tools have been installed properly.

**Comment by alaindargelas** [comment]
Fixed by #1853. Note Verilator does not support this whole testbench (UVM), so no way to verify the hierarchy. This is a Cadence simulation setup only.
Maybe if we try to isolate the DUT, but not sure, it looks like there is UVM all over the place.
