### ISSUE TITLE
Disabling RTTI

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#1718]
RTTI is enabled by default for both gcc & cl compiler. Also, dynamic_cast is being used across the codebase. Use of RTTI at library forces enabling RTTI at the program level which, ideally, we would like to disable it for number of reasons including performance and size.

There are options that can be used to restrict RTTI information to only the classes that need it. Here's an [implementation](https://github.com/DummySphere/cpp-rtti). I am endorsing this implementation but just presenting one such option.

Any thoughts on implementing custom RTTI rather than forcing it to be enabled at program level?

P.S. We use CopperSpice (a fork of Qt) for our UI and the output binary sizes grow by a factor of 2.8 times by enabling RTTI at program level. This is not an ideal solution but UDHM/Surelog is the only library we use that forces enabling RTTI.

**Comment by alaindargelas** [comment]
@hs-apotell any update/path to recoup the 24% runtime increase? If not we have to revert back to stock antlr (Not my fork) with RTTI in the main Surelog as the slowdown is not acceptable on Linux.
You can point to your RTTI-less Antlr implementation in your fork. For the antlr generated code in Surelog and the surelog code itself, I think we can use your RTTI replacement as the dynamic casts are not in the millions per run like in Antlr. 
But first we need to recoup the 24% loss. Please update on your findings.

**Comment by hs-apotell** [comment]
Sorry, juggling multiple priorities. I haven't had chance to evaluate the performance of the solution just yet. As a stop gap solution, can we just point Surelog to use the master branch of Antlr instead of the modified Surelog branch. That would mean using pristine Antlr without the bitfield modifications. I will try get the RTTI version working in next few days. This is critical change for us as well which has to get done but at the immediate moment I need to clear my backlog so I can dedicate some exclusive time on this.

If you are comfortable with this stop gap solution, either drop a comment here so I can create the PR with necessary change or update the .gitmodules yourself.

**Comment by alaindargelas** [comment]
Yes please do create a PR with default main antlr

**Comment by alaindargelas** [comment]
OK, after merging the stock Antlr here are the runtime measurements:

Stock Antlr runs the regression in **1980s**
Antlr with RTTI removed using @hs-apotell's technique runs in **1660s**
My version with the bitfields runs in **1306s.**

I'm adding back the bitfield version under third_party/antlr_fast and make the Surelog cmake point to it meanwhile @hs-apotell experiments with the stock antlr/RTTI-less antlr.
When I ran the experiment a couple of days ago, maybe I was never running the stock Antlr, maybe I was running the antlr with the RTTI removed.

But one correction is that @hs-apotell's version is faster than the stock antlr, just not as fast as the bitfields.

**Comment by alaindargelas** [comment]
@hs-apotell Let's stop using this fork: https://github.com/alainmarcel/antlr4
Either make a fork directly under chipsalliance or propose a new location since you are the one experimenting with stock antlr.
Re-add the antlr subsystem in Surelog when you have a working version that has a performance not too far from the bitfield version.

**Comment by hs-apotell** [comment]
I don't think I have permissions to fork under chipsalliance umberella.

**Comment by alaindargelas** [comment]
@mgielda do you think we can have an antlr fork under ChipsAlliance. That way Surelog/UHDM won't rely on an aobscure fork in my alainmarcel org.

**Comment by hs-apotell** [comment]
@alaindargelas When you get a moment could you please try PR #1825 (or optionally use alainmarcel/antlr4#4)

Build times from chipsalliance/Surelog builds, averaging 2558s

Build | Time
\-------------
2020 | 2257s
2001 | 2628s
1993 | 2712s
1989 | 2627s
1983 | 2570s

Build time from hs-apotell/Surelog build

Build | Time
\------------
99 | 2436s

I am going to kick off a few more runs of the change to get a better average.

**Comment by alaindargelas** [comment]
@hs-apotell can you give me clear instructions on how to pull a draft PR #1825? I'm reading many posts, I can't make head or tail...

**Comment by hs-apotell** [comment]
1.   Go to antlr repository settings
  2.  At the bottom of that page, you will see an option called “Transfer Ownership”. Click that and provide the new owner’s git handle.
  3.  You should receive an email to the registered email address for chipsalliance group.
  4.  Further steps should be self explanatory.
  5.  To switch Surelog to the new repository address, update the url in .gitmodules file and then run the following commands

‘’’
git submodule sync third_party/antlr
git submodule update third_party/antlr
git add third_party/antlr
git commit
‘’’
________________________________

**Comment by alaindargelas** [comment]
@hs-apotell, that was not the question. I still didn't get the OK to transfer the alainmarcel/antlr to chipsalliance. That is on standy.

In the meantime, I need to know how to checkout an unmerged pull request. Do you know how?

**Comment by alaindargelas** [comment]
Got it!
git clone https://github.com/chipsalliance/Surelog
cd Surelog
git submodule update --init --recursive
git fetch origin pull/1825/head:test-rtti
git submodule update --init --recursive
git checkout test-rtti

**Comment by alaindargelas** [comment]
It's still 1700s vs 1300s for the bitfield version.
As long as this is used only on Windows, I'm OK. Submit a complete PR that uses the **third_party/antlr_fast** for Linux and Macos and uses the **third_party/antlr** for Windows only. You can use your RTTI thing in the Surelog code too. That will not make a difference.
