### ISSUE TITLE
clp.setwritePpOutput(false) makes the parser fail

### ISSUE THREAD

**Issue by pieter3d** [chipsalliance/Surelog#1726]
The following code:
```C++
  SURELOG::CommandLineParser clp(&errors, &symbol_table);
  clp.noPython();
  clp.setParse(true);
  clp.setElaborate(true);
  clp.setElabUhdm(true);
  clp.setCompile(true);
  clp.setwritePpOutput(false);
  clp.setWriteUhdm(false);
  clp.parseCommandLine(argc, argv);
````
Results in the following output:
`  SURELOG::CommandLineParser clp(&errors, &symbol_table_);`

Seems things kinda break if `setwritePpOutput` is false.

**Comment by alaindargelas** [comment]
Yep, this option is if you only need the preprocessing to happen in memory and you do something with it not needed the parser (Some application that only cares about the preprocessed "files").
If you need the parsing to happen, then the only flow that is tested/valid for now is if the preprocessor writes the preprocessed files on disk. It could be made all in memory (With a memory cost) and some work that I can't take on. I'd be happy to guide you. 
BTW, so far, all users were OK with this flow(On all OSs). Is there a specific use case that prevents you from writing to disk?

**Comment by pieter3d** [comment]
Ok, understood. No actual problem here, it just seemed like a non-obvious failure, and a little weird for a statically linked library to write out stuff all on its own without being asked or at the very least pointed to a dir. 
But yeah, there's no use case at the moment that causes problems.
