### ISSUE TITLE
Fix "False Positives" on dashboard

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#1887]
Regression tests in CI show green even when there are failures. Here's an example -

https://github.com/chipsalliance/Surelog/actions/runs/1250052241

This is happening for both Windows and Unix builds.

**Comment by alaindargelas** [comment]
@hzeller, can you into this? It has to do with the regression.tcl script never exiting with a 1 return status in case of failures.
I don't  know what happened there, I thought that it did return 1 when diffs at some point in time.

**Comment by alaindargelas** [comment]
restored exit 1 from regression.tcl, will see if that works in CI
