### ISSUE TITLE
Use std::filesystem instead of manhandling paths as strings

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#1979]
We are noticing quite a few issues emerging from use of strings to manage paths. Here are few instances,

* https://github.com/chipsalliance/Surelog/blob/094f1ad629c34d38c0c578f1a8c913eb8d7c1d82/src/SourceCompile/CompileSourceFile.cpp#L94
* https://github.com/chipsalliance/Surelog/blob/094f1ad629c34d38c0c578f1a8c913eb8d7c1d82/src/SourceCompile/CompileSourceFile.cpp#L126

Also, Windows limit of 260 characters applies when using strings are arguments to classes like std::ofstream but it doesn't when using std::fs::path. We are running into the path limit on Windows with certain tests (most recently with BlackParrot) and using std::fs seems to resolve it. Unfortunately, the documented solution to fix the path limit doesn't seem to work for Surelog.

**Comment by hzeller** [comment]
+1 for using fs::path to assemble file names.

**Comment by alaindargelas** [comment]
The BlackParrot test path is not a Surelog specific issue, it is a BlackParrot test structure issue.

**Comment by alaindargelas** [comment]
Yup, please update the minimum gcc, send a PR.

**Comment by hs-apotell** [comment]
For sake of documentation - Found another reason justifying this change. Surelog calling external processes using `system` command and using backslashes on Msys2 causes failure. Specific test case failing as of today is `DiffSimpleIncludeAndMacros` where the input to the `diff` command isn't being found because the input output directory on the command-line was using backslashes.

**Comment by alaindargelas** [comment]
Fixed by #2253
