### ISSUE TITLE
Use of multimaps in FileContent

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#1983]
Just came across something odd so bringing it to notice. In FileContent.h -

https://github.com/chipsalliance/Surelog/blob/6775285b8689a64b0a94d47ef5098cb0837d29e3/src/Design/FileContent.h#L49-L50
https://github.com/chipsalliance/Surelog/blob/6775285b8689a64b0a94d47ef5098cb0837d29e3/src/Design/FileContent.h#L54-L55

Both these containers are declared as `multimap` but not used as the same since I can't find any logic that deals with multiple values per key. 

https://github.com/chipsalliance/Surelog/blob/6775285b8689a64b0a94d47ef5098cb0837d29e3/src/Design/FileContent.cpp#L130-L138
https://github.com/chipsalliance/Surelog/blob/6775285b8689a64b0a94d47ef5098cb0837d29e3/src/Design/FileContent.cpp#L150-L159

Neither implementation is doing a `multimap::equal_range`. Is this an oversight or by design?

**Comment by alaindargelas** [comment]
It's by design, there are tests that contain multiple definitions of the same class or package.
I think I removed the code warning about it, but the containers reflect the design (multiple defs).
