### ISSUE TITLE
OutOfBounds read in ParseFile Line Cache

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2003]
While running BlackParrot test, encountered a out of bounds read in line cache vector in `ParseFile` implementation. I added a check in `ParseFile::getFileId` and `ParseFile::getLineNb` to capture the details. The issue is in `ParseFile::getFileId` with the following context.

```
File: third_party/tests/external/basejump_stl/\bsg_misc/bsg_concentrate_static.v
fileInfoCache.size() = 49
line = 88
````

**Comment by alaindargelas** [comment]
Fixed by #2329
