### ISSUE TITLE
UHDM differences in tcl vs. py

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2026]
This is in context to the specific regression run on the same code base using both tclgen & pygen. I just noticed a few interesting differences and need your input on which one is correct (or complete).

https://github.com/hs-apotell/Surelog/actions/runs/1313693805

You can download the artifacts from the run above and compare the folders. Specific differences -

* For `bit_select`, tclgen doesn't report a `parent` field, pygen does.
* For `ref_obj`, tclgen doesn't report hierarhical names but pygen does.
* For `ref_obj`, tclgen doesn't include `vpiFullName`, pygen does.
* For `parameter`, tclgen report a `'parent` field, pygen doesn't.

[pygen-ArianeElaby.log](https://github.com/chipsalliance/Surelog/files/7306358/pygen-ArianeElaby.log)
[tclgen-ArianeElab.log](https://github.com/chipsalliance/Surelog/files/7306359/tclgen-ArianeElab.log)
 
I have the logs for one such test case which represent the differences across the others. Also, note that these changes are after the modularization pass.

**Comment by Thomasb81** [comment]
Hello

Sorry to hijack this issue, it seems to me that this odd proposition was not yet put on the table in order to avoid to maintain 2 version of the same code generator.  Aka install a tcl interpreter on windows is something very unusual ...

I understand from : https://docs.python.org/3/library/tkinter.html 

> The tkinter package (“Tk interface”) is the standard Python interface to the Tcl/Tk GUI toolkit. Both Tk and tkinter are available on most Unix platforms, including macOS, as well as on Windows systems.
[...]
> The official Python binary release bundles Tcl/Tk 8.6 threaded. 

That standard python installation ship a tcl interpreter. 

I do not have access to a windows workstation with a python installation to test this myself. But if that's work, you can solve your problem of tcl installation on windows and rely on your python installation.

```
#!/bin/env python3

import tkinter
tcl = tkinter.Tcl()
result = tcl.eval('puts $tcl_version')
```

**Comment by alaindargelas** [comment]
It looks like these minor differences come from the clone_tree.cpp implementation. Can I get access to the generated files from Python? I'll try to spot the diff.

**Comment by hs-apotell** [comment]
It does matter because the current output doesn't match this output. Attached are the generated source files.

[generated.zip](https://github.com/chipsalliance/Surelog/files/7307274/generated.zip)

**Comment by alaindargelas** [comment]
We will switch to the python generator shortly and you'll have to maintain it going forward.
We will rebase the log files based on the python generated code. So these diffs will disappear, hence it does not matter.
These differences happen every once in a while, while reordering things in UHDM/Surelog Elaborator. They don't carry strong information (That is not present in any other form).
