### ISSUE TITLE
Errors from system calls are being ignored

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2045]
Errors from `system` calls are being ignored causing issues further down the pipeline. These calls have been failing on Windows.

* https://github.com/chipsalliance/Surelog/blob/3527e31ba8caca92750e0f88afe740af631de498/src/SourceCompile/Compiler.cpp#L467
* https://github.com/chipsalliance/Surelog/blob/3527e31ba8caca92750e0f88afe740af631de498/src/SourceCompile/Compiler.cpp#L476
* https://github.com/chipsalliance/Surelog/blob/3527e31ba8caca92750e0f88afe740af631de498/src/SourceCompile/Compiler.cpp#L598
* https://github.com/chipsalliance/Surelog/blob/3527e31ba8caca92750e0f88afe740af631de498/src/SourceCompile/Compiler.cpp#L605

**Comment by alaindargelas** [comment]
Do not use -mp on Windows nor -lomem those options are specifically creating sub processes.
Instead use -mt that create multithreads on Windows.
