### ISSUE TITLE
Surelog allows to bit-select on real data type

### ISSUE THREAD

**Issue by kamilrakoczy** [chipsalliance/Surelog#2325]
TEST:
```
module top();
        real a = 0.5;
        wire [3:0] b;
        wire c;

        assign c = b[a];
endmodule
```
It is illegal to do bit select on real data type. I'm not sure if tool should detect this and fail, but as it is illegal SystemVerilog code, I think Surelog should also fail on such code.

**Comment by alaindargelas** [comment]
Fixed by #2390
