### ISSUE TITLE
ClangTidy is broken

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/Surelog#2384]
ClangTidy
failed 3 hours ago in 6m 15s
Search logs
2s
2s
52s
26s
4s
0s
4m 48s
/home/runner/work/Surelog/Surelog/third_party/UHDM/third_party/capnproto/c++/src/capnp/schema.c++: In member function ‘capnp::Type capnp::Schema::BrandArgumentList::operator[](capnp::uint) const’:
/home/runner/work/Surelog/Surelog/third_party/UHDM/third_party/capnproto/c++/src/capnp/schema.c++:426:12: warning: ‘*((void*)& result +4)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  426 |     result = Type(static_cast<schema::Type::Which>(binding.which), binding.schema);
      |     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Surelog/Surelog/third_party/UHDM/third_party/capnproto/c++/src/capnp/schema.c++: In member function ‘capnp::Type capnp::Schema::getBrandBinding(uint64_t, capnp::uint) const’:
/home/runner/work/Surelog/Surelog/third_party/UHDM/third_party/capnproto/c++/src/capnp/schema.c++:426:12: warning: ‘*((void*)& result +4)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  426 |     result = Type(static_cast<schema::Type::Which>(binding.which), binding.schema);
      |     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: Leaving directory '/home/runner/work/Surelog/Surelog/build'
[ 19%] Built target capnp
make[3]: Entering directory '/home/runner/work/Surelog/Surelog/build'
make[3]: Leaving directory '/home/runner/work/Surelog/Surelog/build'
make[3]: Entering directory '/home/runner/work/Surelog/Surelog/build'
make[3]: Leaving directory '/home/runner/work/Surelog/Surelog/build'
[ 21%] Built target kj-async
make[3]: Entering directory '/home/runner/work/Surelog/Surelog/build'
make[3]: Leaving directory '/home/runner/work/Surelog/Surelog/build'
make[3]: Entering directory '/home/runner/work/Surelog/Surelog/build'
/home/runner/work/Surelog/Surelog/third_party/UHDM/third_party/capnproto/c++/src/capnp/compiler/node-translator.c++: In member function ‘virtual capnp::uint capnp::compiler::NodeTranslator::StructLayout::Group::addData(capnp::uint)’:
/home/runner/work/Surelog/Surelog/third_party/UHDM/third_party/capnproto/c++/src/capnp/compiler/node-translator.c++:491:45: warning: ‘*((void*)& bestLocation +4)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  491 |         return parentDataLocationUsage[*best].allocateFromHole(
      |                                             ^
/home/runner/work/Surelog/Surelog/third_party/UHDM/third_party/capnproto/c++/src/capnp/compiler/node-translator.c++: In member function ‘capnp::Orphan<capnp::List<capnp::schema::Annotation, capnp::Kind::STRUCT> > capnp::compiler::NodeTranslator::compileAnnotationApplications(capnp::List<capnp::compiler::Declaration::AnnotationApplication, capnp::Kind::STRUCT>::Reader, kj::StringPtr)’:
/home/runner/work/Surelog/Surelog/third_party/UHDM/third_party/capnproto/c++/src/capnp/compiler/node-translator.c++:3280:14: warning: ‘*((void*)& kind +2)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 3280 |       } else if (*kind != Declaration::ANNOTATION) {
      |              ^~
make[3]: Leaving directory '/home/runner/work/Surelog/Surelog/build'
[ 23%] Built target capnpc
make[3]: Entering directory '/home/runner/work/Surelog/Surelog/build'
make[3]: Leaving directory '/home/runner/work/Surelog/Surelog/build'
make[3]: Entering directory '/home/runner/work/Surelog/Surelog/build'
make[3]: Leaving directory '/home/runner/work/Surelog/Surelog/build'
[ 23%] Built target capnp-json
make[3]: Entering directory '/home/runner/work/Surelog/Surelog/build'
make[3]: Leaving directory '/home/runner/work/Surelog/Surelog/build'
make[3]: Entering directory '/home/runner/work/Surelog/Surelog/build'
make[3]: Leaving directory '/home/runner/work/Surelog/Surelog/build'
[ 23%] Built target capnp_tool
make[3]: Leaving directory '/home/runner/work/Surelog/Surelog/build'
[ 23%] Built target capnpc_cpp
make[3]: Entering directory '/home/runner/work/Surelog/Surelog/build'
make[3]: Leaving directory '/home/runner/work/Surelog/Surelog/build'
make[3]: Entering directory '/home/runner/work/Surelog/Surelog/build'
Traceback (most recent call last):
  File "/home/runner/work/Surelog/Surelog/third_party/UHDM/scripts/generate.py", line 7, in <module>
    import loader
  File "/home/runner/work/Surelog/Surelog/third_party/UHDM/scripts/loader.py", line 1, in <module>
    import orderedmultidict
ModuleNotFoundError: No module named 'orderedmultidict'

**Comment by Thomasb81** [comment]
additional  reference https://github.com/chipsalliance/UHDM/issues/602
