### ISSUE TITLE
Inaccurate column information and missing end location information in error messages

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2406]
In most of the cases in preprocess, parse and elaboration, the reported error messages are missing the column information. They seem to be defaulted to zero in most cases. Here are a few such cases -

* https://github.com/chipsalliance/Surelog/blob/136d59f1baa2857accb0d39171bf950474780687/src/Design/Design.cpp#L128-L129
* https://github.com/chipsalliance/Surelog/blob/136d59f1baa2857accb0d39171bf950474780687/src/Design/Design.cpp#L366-L368
* https://github.com/chipsalliance/Surelog/blob/136d59f1baa2857accb0d39171bf950474780687/src/Design/FileContent.cpp#L97-L99
* https://github.com/chipsalliance/Surelog/blob/136d59f1baa2857accb0d39171bf950474780687/src/DesignCompile/CompileClass.cpp#L88-L89

Also, `Location` should include end location (both line and column).

Accurate location information is critical for language servers and linters to work correctly.

**Comment by alaindargelas** [comment]
Please contribute PRs, I don't have time to work on this.

**Comment by alaindargelas** [comment]
That seems to be largely fixed by #2963
