### ISSUE TITLE
Build breaks when UHDM includes change

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2572]
Files included in UHDM model headers changed in PR chipsalliance/UHDM#635. That change itself shouldn't have had any impact on Surelog whatsoever but still Surelog build broke. Surelog isn't including the files what it uses in both headers and source files. External library changes of this nature shouldn't have an impact (especially, given that UHDM itself compiled and all of its own test cases passed).

What's the approach going forward? Is Surelog meant to depend on public header i.e. uhdm.h or is it expected to cherry-pick individual files that it actually needs. And what about use of Surelog.h within the library implementation itself? Also, headers are including a lot of other files that it could potentially forward declare. Is this by design?

Given the big impact noticed in UHDM (library file size reduced from 3.4 GB to 210 MB, and build times dropped to one-third) merely by optimizing the header includes, I think Surelog deserves a similar update.

@alaindargelas @hzeller Thoughts?

**Comment by hs-apotell** [comment]
Personally, I like CI telling me I did something wrong. I don't want it to fix it for me.

That said, I think, Surelog needs a pass to fix the include headers - regardless of whether it is part of CI or not. With code already cleaned up it will _easier_ to enable checks on CI.

Are we open to taking a large change just to fix the header includes? I can do that over the weekend.

Heads up - chipsalliance/UHDM#635 currently cannot be merged into Surelog. Build fails with lot of compile errors.

**Comment by hzeller** [comment]
Yes, the CI will only complain, no fix. So we do need first to do the cleanup.

I often create large cleanup changes and @alaindargelas is typically fine with it. In particular if the cleanup is mostly pretty mechanical changes.

**Comment by alaindargelas** [comment]
The break in Surelog is pretty trivial, it looks like UHDM::VectorOfany definition disappeared from the include file Surelog includes from UHDM

**Comment by alaindargelas** [comment]
There are tons of changes in that changelist which are not just files moving around, or forward declaration changing. One cannot presume anything from this changelist.
That statement " That change itself shouldn't have had any impact on Surelog whatsoever but still Surelog build broke. " is incorrect.

**Comment by hs-apotell** [comment]
#2644 Fixes this issue.
