### ISSUE TITLE
doesn't build clean on ubuntu20

### ISSUE THREAD

**Issue by mattvenn** [chipsalliance/Surelog#2575]
Following the instructions from simview:

Install pre-requisite packages (Ubuntu 20.04 LTS)
sudo apt install build-essential cmake git pkg-config tclsh swig uuid-dev libgoogle-perftools-dev python3 python3-dev default-jre lcov libncurses-dev
Build and install [Surelog](https://github.com/chipsalliance/Surelog)
git clone git@github.com:chipsalliance/Surelog.git
cd Surelog
git submodule update --init --recursive
make
sudo make install

I get this error:

[ 38%] Linking CXX executable capnpc-c++
make[3]: Leaving directory '/tmp/Surelog/build'
[ 38%] Built target capnpc_cpp
make[3]: Entering directory '/tmp/Surelog/build'
Scanning dependencies of target GenerateCode
make[3]: Leaving directory '/tmp/Surelog/build'
make[3]: Entering directory '/tmp/Surelog/build'
[ 38%] Generating generated/src/UHDM.capnp
Traceback (most recent call last):
  File "/tmp/Surelog/third_party/UHDM/scripts/generate.py", line 7, in <module>
    import loader
  File "/tmp/Surelog/third_party/UHDM/scripts/loader.py", line 1, in <module>
    import orderedmultidict
ModuleNotFoundError: No module named 'orderedmultidict'
make[3]: *** [third_party/UHDM/CMakeFiles/GenerateCode.dir/build.make:386: third_party/UHDM/generated/src/UHDM.capnp] Error 1
make[3]: Leaving directory '/tmp/Surelog/build'
make[2]: *** [CMakeFiles/Makefile2:1207: third_party/UHDM/CMakeFiles/GenerateCode.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 38%] Generating generated/src/SourceCompile/VObjectTypes.h, generated/src/SourceCompile/VObjectTypes.cpp, generated/src/API/VObjectTypes_py.h, generated/src/SourceCompile/SV3_1aTreeShapeListener.h, generated/src/SourceCompile/SV3_1aPpTreeShapeListener.h
---------- VObjectTypes, Listener generation
make[3]: Leaving directory '/tmp/Surelog/build'
[ 38%] Built target GenerateParser
make[2]: Leaving directory '/tmp/Surelog/build'
make[1]: *** [Makefile:163: all] Error 2
make[1]: Leaving directory '/tmp/Surelog/build'
make: *** [Makefile:26: release] Error 2

**Comment by mithro** [comment]
You don't seem to have installed the orderedmultidict Python module?

**Comment by hzeller** [comment]
@mattvenn I've [fixed the install instructions](https://github.com/pieter3d/simview/pull/6) in https://github.com/pieter3d/simview ... which is where you probably stumbled upon this.

To address the documentation issue in the respective projects, there is now these open pull requests
  https://github.com/chipsalliance/UHDM/pull/639
  https://github.com/chipsalliance/Surelog/pull/2577

And there are issues to proactively check for the relevant build dependencies in cmake to have the error less obscure:
  https://github.com/chipsalliance/Surelog/issues/2576
  https://github.com/chipsalliance/UHDM/issues/640
