### ISSUE TITLE
Array index out of bounds error

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2615]
Test: Earlgrey_Verilator_01_05_21
Location: https://github.com/chipsalliance/Surelog/blob/d7f4699f9405656977857b71447b58f2fe58cefc/src/DesignCompile/CompileExpression.cpp#L5692-L5694

val = 20000000000000000
steps = 1
l = 17

Use of unsigned int for indexing causes the number to wrap around.

**Comment by alaindargelas** [comment]
Fixed by #2620
