### ISSUE TITLE
Surelog headers need to be rooted

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2624]
Surelog currently installs without a rooted folder causing conflicts with other libraries. The following are too generic for file names to not have conflicts with other libraries. This is forcing an order to our include paths which isn't desirable.

* Config/Config.h
* Library/Library.h
* Design/Design.h

Can we move Surelog headers into 'include/Surelog' folder to avoid this frustration? All include paths will have to fixed to accommodate the move.

Also, header guards needs to be fixed as well to include the namespace. CONFIG_H and LIBRARY_H aren't specific enough. They should preferably be SURELOG_CONFIG_H & SURELOG_LIBRARY_H.

@alaindargelas @hzeller Comments? Thoughts?

**Comment by alaindargelas** [comment]
Fixed by #2633
