### ISSUE TITLE
support for windows?

### ISSUE THREAD

**Issue by seandogg2** [chipsalliance/Surelog#2668]
I tried two different methods to compile for Windows:

1. In cygwin, I get an error (presumably) related to passing a cygwin path to Java. It is on line 100 in "GenerateParser.dir/build.make".
2. When I generate a solution from CMake for Visual Studio 2017, I get a compile error in ProcessFile.cpp (line 641, std::isalpha expects 2 arguments but only 1 is provided)

I am not immediately in a position to compile on Linux, but I assume these problems would not happen there. Is there any plan to support Windows?

**Comment by alaindargelas** [comment]
Both cygwin and VS are supported, running and fully passing in CI: https://github.com/chipsalliance/Surelog/actions/runs/1891104139
Can you compare your setup against the one we are using for CI?
https://github.com/chipsalliance/Surelog/blob/master/.github/workflows/main.yml

**Comment by hs-apotell** [comment]
Both VS2019 and VS2022 are officially supported and building successfully on CI and local. Please check your local setup.

**Comment by alaindargelas** [comment]
@seandogg2 can we close this?

**Comment by seandogg2** [comment]
Yes. I haven't had time to try, but there are some differences in my
environment.
