### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by little-blue** [chipsalliance/Surelog#2740]
I follow the UHDM-integration [https://github.com/chipsalliance/UHDM-integration-tests](url) to build the toolchain, while when I execute `./build_binaries.sh`, there always meet an error
`yosys-uhdm-plugin-integration/Surelog/src/DesignCompile/UhdmChecker.cpp:249:42: error: ‘setprecision’ is not a member of ‘std’`
and
`yosys-uhdm-plugin-integration/Surelog/src/DesignCompile/UhdmChecker.cpp:315:67: error: ‘setw’ is not a member of ‘std’`
I think it is because this file forget to 
`#include <iomanip>`
add this line and build will succeed.

**Comment by alaindargelas** [comment]
Please submit a PR with the change.
