### ISSUE TITLE
Protecting the master branch.

### ISSUE THREAD

**Issue by QuantamHD** [chipsalliance/Surelog#2744]
It looks like I inadvertently committed directly to the master branch. 75d6eb78e9c2c061cf5afb2052707788133175b9

I'm going to revert this commit, but I think to prevent future accidents turning on branch protection would be good unless there's a good reason not to.

**Comment by alaindargelas** [comment]
Please make the necessary change.

**Comment by QuantamHD** [comment]
@alaindargelas I don't believe I have the permission to change that particular permission. 

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by alaindargelas** [comment]
Done
