### ISSUE TITLE
Remove patched Surelog in favor of upstream patch.

### ISSUE THREAD

**Issue by QuantamHD** [chipsalliance/Surelog#2755]
I worked with the upstream ANTLR team to integrate a faster RTTI implementation into ANTLR. When this PR https://github.com/antlr/antlr4/pull/3584 is merged in, the forked version of ANTLR in Surelog will have no definable benefits over upstream. 

If this patch is merged we should move to upstream ANTLR.

**Comment by QuantamHD** [comment]
It's merged in the dev branch upstream. Shall we update the submodule?

**Comment by alaindargelas** [comment]
Experiments still show Surelog version is 40% faster than the Antlr 4.10 dev branch.
Waiting for further improvements in Antlr 4.10

**Comment by alaindargelas** [comment]
Will be addressed by #2845
