### ISSUE TITLE
"let" declarations aren't part of UHDM model

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2782]
Test: Assertions

`let` declarations are not part of UHDM model.

**Comment by alaindargelas** [comment]
let expressions have to be inlined like macros.
They are not going to show in the UHDM model, they are going to be inlined with parameter substituted.

**Comment by alaindargelas** [comment]
let expressions have to be inlined like macros.
They are not going to show in the UHDM model, they are going to be inlined with parameter substituted.

**Comment by hs-apotell** [comment]
What is `design::Let_decl` supposed to be then? If all let expressions are inlined then this call would always return an empty vector.
