### ISSUE TITLE
antlr4 build should be optional

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/Surelog#28]
Unlike flatbuffer, antlr4 is commonly installable on regular workstation:

```
$ sudo apt-get install antlr4
$ antlr4 | head -1
ANTLR Parser Generator  Version 4.7.2
```

So in the case it already exists, we should avoid building `antlr4` as part of the build dependencies (it is probably still a good idea to keep building instructions for it available for hermetic build situations in CI environments. But by default, our CMake should check if it is available in the correct version.)

**Comment by alaindargelas** [comment]
We have established the off the shelve antlr is not really usable (Speed issue or code bloat on Windows).
