### ISSUE TITLE
Successive runs with cache enabled generates different UHDM output

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2806]
Two consecutive runs of Surelog, with no change and cache enabled, generates different UHDM output. First run has correct `ref_obj/actual_group` bindings. In the second run, however, many `ref_obj/actual_group` bindings are null. Also, many `vpiNet` objects are missing in the second run.

Test - Assignments

Attached are the two log files from consecutive runs.
[FirstRun.log](https://github.com/chipsalliance/Surelog/files/8395566/FirstRun.log)
[SecondRun.log](https://github.com/chipsalliance/Surelog/files/8395567/SecondRun.log)

**Comment by alaindargelas** [comment]
Fixed by #2817
