### ISSUE TITLE
Static functions

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2819]
Missing model property to declare a function as _static_

There was a change #2277 to parse static functions but the property is being ignored.

**Comment by alaindargelas** [comment]
It's correct default lifetime is static, if you add the automatic keyword before the function, you'll see the automatic property.

**Comment by alaindargelas** [comment]
It's correct default lifetime is static, if you add the automatic keyword before the function, you'll see the automatic property.
