### ISSUE TITLE
$signed/$unsigned sys func support

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/Surelog#2844]
parameter olen = width_z;
parameter ilen = signd_a ? [width_a](https://source.corp.google.com/piper///depot/google3/platforms/argos/logic/dionysus/ip/bo/hw_bigocean_2160p_vp9c_h264e_av1c/out/me_round1_calc.v;l=486?q=%22$signed%22&ss=piper%2FGoogle%2FPiper:google3%2Fplatforms%2Fargos%2Flogic%2Fdionysus%2Fip%2Fbo%2Fhw_bigocean_2160p_vp9c_h264e_av1c%2F) : width_a+1;
parameter len = (ilen >= olen) ? ilen : olen;
result_t = $signed( {(len){sbit}} ); // not supported
result_t[width_a-1:0] = arg1;

**Comment by QuantamHD** [comment]
Any update on this Alain? Would be happy to help implement if you have other tasks right now. I just need a bit of direction on where to look.

**Comment by alaindargelas** [comment]
Fixed by #2868
