### ISSUE TITLE
'import' is a keyword in C++20

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2855]
There's a UHDM model named import which doesn't compile with C++20. I would like to change this.

Should it be renamed 'import_stmt' or 'import_typespec'. It is a subclass of `typespec` but this isn't really a data type but 'import_typespec' would be consistent with all other subclasses of `typespec`.

**Comment by alaindargelas** [comment]
Change it to import_typespec I forgot exactly why we made it a child of typespec, I think it is saved in a typespec container.

**Comment by alaindargelas** [comment]
Fixed by #2860
