### ISSUE TITLE
Segfault on Windows TestSepCompNoHash

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/Surelog#2957]
@hs-apotell, can you check what is happening there?

https://github.com/chipsalliance/Surelog/runs/6545609323?check_suite_focus=true

Is it a real segfault? or just the script is not executed correctly?

**Comment by alaindargelas** [comment]
@hs-apotell, can we write those scripts in a operating system agnostic way? 
They are very simple list of commands. Those tests should be validated on Windows too.
Fixed by #2959

**Comment by hs-apotell** [comment]
Opened #2961. Will revisit as time permits.
