### ISSUE TITLE
Add support for Clang on Windows

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2982]
At the moment antlr doesn't build successfully with Clang on Windows. Need a few minor tweaks to the CMakeFile.txt to make it succeed.

Note: The goal is to support Clang/LLVM and NOT Clang-cl. The latter is M$ version of Clang that deviates heavily from standard.

**Comment by hs-apotell** [comment]
@hzeller Could you assist in promoting [this](https://github.com/antlr/antlr4/pull/3678) PR to dev? These are few changes to antlr4 Cpp runtime CMakeFiles.txt to support building with Clang on Windows.

**Comment by hzeller** [comment]
This looks like it is complete ?

**Comment by hs-apotell** [comment]
Fixed by #3098 & #3100
