### ISSUE TITLE
Print UhdmId by default in Uhdm output in logs

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2985]
Any reason the default is set to false? The ID information help's track a lot of issues and has been very handy in identifying issues.

Can we toggle the flag as default?

**Comment by alaindargelas** [comment]
Sure, it was very unstable at the beginning of the project since every time there is a new type of node or simply any new node added it shifts the IDs by the number of new nodes introduced. But things are stabilizing now. Add -d vpi_ids

**Comment by hs-apotell** [comment]
Fixed by #2988
