### ISSUE TITLE
Add a way to specify blackbox modules on the surelog command line

### ISSUE THREAD

**Issue by QuantamHD** [chipsalliance/Surelog#3021]
For hierarchical synthesis it would be useful to specify certain modules as black boxes.

Something like `surelog -blackbox a b c d ...`

**Comment by alaindargelas** [comment]
@QuantamHD, please try #3022.
My suspicion is that it is not the whole solution. We probably have to have the interface to the blackbox (ports, parameters) dump in the UHDM db to be able to do the stitching. But let me know.

**Comment by alaindargelas** [comment]
Open another issue if need be. But this looks like this is fixed in the current use case.
