### ISSUE TITLE
Why is SymbolId 64 bit?

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3057]
Why is SymbolId 64 bit long while cache only supports 24 bits? Shouldn't it be 32 bit long??

UHDM::SymbolFactory::ID is 32 bits but SURELOG::RawSymbolId is 64 bit.

**Comment by alaindargelas** [comment]
That might be an oversight.
To test with 32 bit, you need to run the largest design that are blacklisted (BlackParrot...)
We should also print the highest SymbolId created to measure what is the range.
