### ISSUE TITLE
rountrip executable infinite loop

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/Surelog#3064]
With the latest changes in elab #3063, that executable goes into infinite loop

**Comment by hs-apotell** [comment]
Any more information? Any specific test in focus or is that across the board for all tests??

**Comment by hs-apotell** [comment]
The infinite loop is during elaboration process. ModPort -> Interface -> ModPort. Tnoc is one such test.

**Comment by hs-apotell** [comment]
PR #3065 should stop the infinite loop (RoundTrip doesn't do an explicit elaboration anymore) but the issue with elaboration still persists.

**Comment by alaindargelas** [comment]
See comment in PR if you need to re-enable elaboration in that executable.
