### ISSUE TITLE
CI "pages build and deployment" keeps failing

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/Surelog#3112]
Example:
https://github.com/chipsalliance/Surelog/runs/7373265893?check_suite_focus=true

Where is this even configured ? It sounds like something @mithro or @umarcor would know.

**Comment by hzeller** [comment]
I don't have access to the settings of this project (@alaindargelas  can I has more admin access to Surelog?)

**Comment by mithro** [comment]
@hzeller - I believe I have fixed your permissions level to do that.

**Comment by hzeller** [comment]
Yes that worked, thanks @mithro 

@umarcor indeed, it was configured to serve from the master branch. I set it to 'None', as there is no documentation or no pages branch.
