### ISSUE TITLE
Evaluating function in module

### ISSUE THREAD

**Issue by aolofsson** [chipsalliance/Surelog#3132]
This code simulats ok in icarus, but I get the following message in Surelog. This is nastier than my usual code, so I may be missing something in the standard here.

The snippet is inside a module...

```sv
 function automatic [7:0] offset;
      input [7:0] i;
      input [63:0] vector;
      integer 	    ii;
      begin
	 offset = 0;
	 for(ii=0; ii<i; ii=ii+1)
	   offset = offset + vector[ii*8+:8];
      end
   endfunction

 for(i=0;i<SECTIONS;i=i+1)
     begin: ila_section
	// figure out how many bits came before
	localparam [7:0] START = offset(i,NIO)
	localparam [7:0] N = NPIO[8*i+:8]
   

```

**Surelog Error:**

ERR:CP0337] <REDACTED> Undefined user task/function "offset".

**Comment by alaindargelas** [comment]
@aolofsson, same comment, I'm trying to reverse engineer a workable testcase from the snippet, can you provide a complete snippet that compiles with all variables/params declared, that is encompassed with module/endmodule?

**Comment by alaindargelas** [comment]
@aolofsson how about this one? Is is fixed too?

**Comment by aolofsson** [comment]
I found a way around that construct so the code is "gone". I recommend closing it.

**Comment by alaindargelas** [comment]
OK, thanks
