### ISSUE TITLE
Plugin test fails due to missing Python Module

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/Surelog#3143]
It looks like it is failing at some 'skbuild' Python module
https://github.com/chipsalliance/Surelog/runs/7710326771?check_suite_focus=true#step:8:20

**Comment by hzeller** [comment]
Assigning to Tom to triage.

**Comment by tgorochowik** [comment]
This is an issue with new cmake from pip. I think we should bump the distro version here too, which coincidentally fixes this issue as well. As a quick fix we can pin cmake to an older version
