### ISSUE TITLE
False UHDM ObjectStat??

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3202]
UHDM ObjectStat doesn't represent the number of objects of each type _in the tree_. It rather represents the number of objects of each type that ever got constructed. IMHO, what's needed (and useful) is the number of objects of each type in the tree.

@alaindargelas opinion?

**Comment by alaindargelas** [comment]
No opinion, this is not useful to me. I diff the UHDM outputs. Number of objects don't tell me anything.

**Comment by alaindargelas** [comment]
You must have a unitialized memory read in your code. Need to run valgrind on the test.

**Comment by alaindargelas** [comment]
I mean I diff visually the UHDM output, I don't rely on any number at all.
