### ISSUE TITLE
test-plugin test is broken

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/Surelog#3362]
There was a change in the API of SynthSubset class some time back. 
The plugin didn't get updated in this test:
https://github.com/chipsalliance/Surelog/actions/runs/3551926372/jobs/5966501132

**Comment by rkapuscik** [comment]
This was fixed with https://github.com/chipsalliance/yosys-f4pga-plugins/pull/407 (merged two days ago, last Surelog build is four days old). I'll update the integration repository and rerun the CI to verify.

**Comment by rkapuscik** [comment]
Updated the integration repository (https://github.com/antmicro/yosys-systemverilog/pull/1313), the Surelog test now passes, see https://github.com/chipsalliance/Surelog/actions/runs/3551926639.
