### ISSUE TITLE
ubuntu20, make fatal error, need help

### ISSUE THREAD

**Issue by chenfengrugao** [chipsalliance/Surelog#3363]
Hello, does anyone meet this error: 
![image](https://user-images.githubusercontent.com/32785798/205027832-388ef679-af72-4b75-b952-471e56618fbc.png)

**Comment by alaindargelas** [comment]
Please provide:
- Ubuntu exact version
- gcc version
- RAM memory size

Also try to limit the number of compilation processes:
make -j 2

**Comment by chenfengrugao** [comment]
Thanks for your help. It's the reason of RAM size. I enlarged the swap size and it has passed.
