### ISSUE TITLE
Potential bug in ExprEval::reduceExpr

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3365]
Did you mean ~val & not !val here ??

https://github.com/chipsalliance/UHDM/blob/5d9dff7b05f73187287fae76fe2f020eb16fe2d6/templates/ExprEval.cpp#L2561

```
if (size == 1) {
  val = !val;        // val's defined as uint64_t so !val should probably be ~val
} else {
  uint64_t mask = getMask(size);
  val = ~val;
  val = val & mask;
}
```

**Comment by alaindargelas** [comment]
@hs-apotell Do you have a testcase that shows an actual issue? If not, then this is a non-issue.
