### ISSUE TITLE
"module" is now reserved in C++

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3381]
UHDM uses "module" as a model name. This doesn't build with C++20. Looking for suggestions on fixing this.

There are a few other names that also cause problems across platform. "interface" is reserved under Windows.

Following the convention used for other such scenarios, Would module_stmt & interface_stmt be acceptable?

Related issue: chipsalliance/UHDM#831

**Comment by alaindargelas** [comment]
It would have to be module_inst and interface_inst
