### ISSUE TITLE
Should nocache also mean no-precompile cache?

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3410]
As implemented, nocache option disables use of precompiled cache as well. Is that expected behavior?

The reason to bring this up - With nocache option enabled some of the test cases (like MiniAmiq) fail. I narrowed it down to order in which the files are preprocessed. Also, MiniAmiq does have any input files except for the UVM files. Is that correct?

**Comment by alaindargelas** [comment]
No it should not. Precompiled packages require very seldom to be compiled (New build, change in grammar).
When changing the grammar, I don't want to re-incur the cost of pre-compiled packages unless necessary (After finalizing the changes).

**Comment by alaindargelas** [comment]
MiniAmiq contains the UVM package plus the sva files (not part of default UVM).
