### ISSUE TITLE
Git tag 0.0 does not match project version 1.48

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/Surelog#3520]
After an update I get:

~/Surelog$ make
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=OFF  -S . -B build
CMake Error at CMakeLists.txt:81 (message):
  Git tag 0.0 does not match project version 1.48.  Did you forget to update
  project version in CMakeLists.txt?

-- Configuring incomplete, errors occurred!
make: *** [Makefile:46: run-cmake-release] Error 1

**Comment by timkpaine** [comment]
We can remove soon (@hzeller has done the required CI changes) but have you run a `git fetch --all` recently? You have out of date git tags.

With the recently merged changes, the cmakelists is the single source of version truth and we can get rid of the git check (here and UHDM).

**Comment by hzeller** [comment]
The [tag v1.48](https://github.com/chipsalliance/Surelog/releases/tag/v1.48)
should be there on hash 71eb4028f18d6b12833578fbcfa4db7b06869f78 
So if it is not there, probably the suggested `git fetch --all` should help.
