### ISSUE TITLE
pkg-config: sometimes libdir is ${PREFIX}/lib64

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/Surelog#3535]
I have encountered a machine in which the library did not end up in `${prefix}/lib/surelog` but `${prefix}/lib64/surelog`. In the [template file for Surelog.pc](https://github.com/chipsalliance/Surelog/blob/master/cmake/configs/Surelog.pc.in#L3) this is hardcoded to `${prefix}/lib`, so linking a project does not work in that case.

What should happen instead is to replace the path where cmake _actually_ installs it, so hopefully there are variables where this can be extracted from.

**Comment by timkpaine** [comment]
we can replace  `CMAKE_INSTALL_LIBDIR` and `CMAKE_INSTALL_INCLUDEDIR` in the pkg-config template file
