### ISSUE TITLE
FindUHDM.cmake still needed ?

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/Surelog#3553]
The [cmake/modules/FindUHDM.cmake](https://github.com/chipsalliance/Surelog/blob/803b2ca762698e3bd2010d4fbc1302ad0120221e/cmake/modules/FindUHDM.cmake) was needed before [UHDM created its own cmake config](https://github.com/chipsalliance/UHDM/blob/f842443f9716eec8ce8afcc38a789029aa28401b/CMakeLists.txt#L360-L366).

Can this now be simplified to use what is generated from the UHDM library ?

**Comment by timkpaine** [comment]
Yep not needed, will do a PR tonight
