### ISSUE TITLE
Use cstdint types across the board

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3572]
There's a mixture of numeric types used in UHDM and Surelog - int, unsigned, unsigned int long, long long, etc

Can we enforce use of standard defined types like int32_t, uint32_t, int64_t, etc??

For whatever isn't available, define an explicit type in something like _config.h_.

**Comment by alaindargelas** [comment]
Sure, please submit respective PRs.

**Comment by alaindargelas** [comment]
Fixed by #3580
