### ISSUE TITLE
Wrong reduction of cast when casting function result.

### ISSUE THREAD

**Issue by kamilrakoczy** [chipsalliance/Surelog#3663]
Related to: https://github.com/chipsalliance/Surelog/issues/3655

TEST:
```
module top(output int o);
   typedef enum logic [2:0] {
      A = 3'b000,
      B = 3'b111
   } sp2v_e;

   function automatic sp2v_e [1:0] get_BA();
      sp2v_e [1:0] out;
      out[0] = B;
      return out;
   endfunction

   assign o = int'(get_BA());
endmodule
```
UHDM:
```
   |vpiContAssign:
   \_cont_assign: , line:13:11, endln:13:29
     |vpiRhs:
     \_constant: 
       |vpiDecompile:0
       |vpiSize:32
       |UINT:0
       |vpiConstType:9
     |vpiLhs:
     \_ref_obj: (o), line:13:11, endln:13:12
       |vpiParent:
       \_cont_assign: , line:13:11, endln:13:29
       |vpiName:o
       |vpiActual:
       \_int_var: (work@top.o), line:1:23, endln:1:24
```
Now surelog lacks information about ``get_BA()`` and reduces it to ``0``. 
edit:
I see that Surelog already had this test, but now it includes also ``out[1] = A;``: https://github.com/chipsalliance/Surelog/pull/3662/files#diff-b40ab63cc59bb1513c2dc9ad693d5692d0473508b4799bcf2e225d9d369175f9R12

Does it mean, that this test without ``out[1] = A;`` isn't valid test case or correct value in such case is ``0``?

**Comment by alaindargelas** [comment]
That is correct, without the out[1] = A;
out is essentially equal to xxx111  (1/2 of the bits have Unknown value as they are undriven), the current test as you have it does not make much sense in terms of design, 
This is why I made the change to the Surelog test, so the test makes sense and out is fully qualified (000111).
I suggest you fix your test too.
