### ISSUE TITLE
bit_select in hier_path

### ISSUE THREAD

**Issue by wsipak** [chipsalliance/Surelog#3691]
Consider this test:

    module top(output int o);
       typedef struct packed {
          logic [9:0] min_v;
       } filter_ctl_t;

       filter_ctl_t [1:0][2:0] a;
       assign a[0][0].min_v = '1;
    endmodule

I think the access to `a[0][0].min_v` is not processed correctly.

The UHDM tree I'm getting for the hier path is:

    \_hier_path: (a[0][0].min_v), line:7:11, endln:7:12
      |vpiParent:
      \_cont_assign: , line:7:11, endln:7:29
      |vpiName:a[0][0].min_v
      |vpiActual:
      \_bit_select: (a), line:7:11, endln:7:12
        |vpiParent:
        \_ref_obj: (a[0])
          |vpiParent:
          \_hier_path: (a[0][0].min_v), line:7:11, endln:7:12
          |vpiName:a[0]
        |vpiName:a
        |vpiIndex:
        \_constant: , line:7:13, endln:7:14
          |vpiParent:
          \_bit_select: (a), line:7:11, endln:7:12
          |vpiDecompile:0
          |vpiSize:64
          |UINT:0
          |vpiConstType:9
      |vpiActual:
      \_bit_select: (a[0][0].min_v), line:7:13, endln:7:14
        |vpiParent:
        \_hier_path: (a[0][0].min_v), line:7:11, endln:7:12
        |vpiFullName:a[0][0].min_v
        |vpiIndex:
        \_constant: , line:7:16, endln:7:17
          |vpiParent:
          \_bit_select: (a[0][0].min_v), line:7:13, endln:7:14
          |vpiDecompile:0
          |vpiSize:64
          |UINT:0
          |vpiConstType:9
      |vpiActual:
      \_ref_obj: (min_v)
        |vpiParent:
        \_hier_path: (a[0][0].min_v), line:7:11, endln:7:12
        |vpiName:min_v

The first `_bit_select` points to `a`, but the second has `a[0][0].min_v` which looks a bit off.

The PR https://github.com/chipsalliance/Surelog/pull/3670 also affects the contents of the tree for this test and the result doesn't look correct either:

    \_hier_path: (a[0][0].min_v), line:7:11, endln:7:12
      |vpiParent:
      \_cont_assign: , line:7:11, endln:7:29
      |vpiName:a[0][0].min_v
      |vpiActual:
      \_bit_select: (a[0][0].min_v.a), line:7:11, endln:7:12
        |vpiParent:
        \_hier_path: (a[0][0].min_v), line:7:11, endln:7:12
        |vpiName:a
        |vpiFullName:a[0][0].min_v.a
        |vpiIndex:
        \_constant: , line:7:13, endln:7:14
          |vpiParent:
          \_bit_select: (a[0][0].min_v.a), line:7:11, endln:7:12
          |vpiDecompile:0
          |vpiSize:64
          |UINT:0
          |vpiConstType:9
      |vpiActual:
      \_bit_select: (a[0][0].min_v), line:7:13, endln:7:14
        |vpiParent:
        \_hier_path: (a[0][0].min_v), line:7:11, endln:7:12
        |vpiFullName:a[0][0].min_v
        |vpiIndex:
        \_constant: , line:7:16, endln:7:17
          |vpiParent:
          \_bit_select: (a[0][0].min_v), line:7:13, endln:7:14
          |vpiDecompile:0
          |vpiSize:64
          |UINT:0
          |vpiConstType:9
      |vpiActual:
      \_ref_obj: (min_v)
        |vpiParent:
        \_hier_path: (a[0][0].min_v), line:7:11, endln:7:12
        |vpiName:min_v

**Comment by wsipak** [comment]
[surelog-a85ff7-uhdm.txt](https://github.com/chipsalliance/Surelog/files/11635122/surelog-a85ff7-uhdm.txt)

**Comment by alaindargelas** [comment]
Fixed by #3697
