### ISSUE TITLE
Unsized constant width

### ISSUE THREAD

**Issue by wsipak** [chipsalliance/Surelog#3692]
Consider this test:

    module top;
        logic [63:0] s1c;
        assign s1c = '1 << 8;
    endmodule

According to the SystemVerilog standard, `'1` would mean setting all bits to `'1`, and then there's the shift of 8 bits.
Surelog reports `'1 << 8` as a constant:

    \_constant:
      |vpiDecompile:256
      |vpiSize:64
      |UINT:256
      |vpiConstType:9

I think this is incorrect, I would expect the result to be equivalent to:
`64'b 1111111111111111111111111111111111111111111111111111111100000000`.

**Comment by alaindargelas** [comment]
Fixed by #3696
