### ISSUE TITLE
Parenting, Instancing & Uniquification

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3704]
In certain cases, _typespec_ and _constant_ aren't cloned since the cloning logic is explicitly wrapped with check for ```ElaboratorListener::uniquifyTypespec```.

How is parenting & instancing expected to work along side unification if these instances are shared?

**Comment by alaindargelas** [comment]
The parent should point to the non-elaborated parent. It should not be updated to point to an instance.

**Comment by alaindargelas** [comment]
@hs-apotell, please submit the PR to complete the cloning for all objects including constants and typespecs, 
please make some memory consumption measurement too.
We might be able to recoup some of the memory increase by completing the garbage collection routine I started (Which also requires decoupling the non-elaborated and elaborated tree).

**Comment by alaindargelas** [comment]
This is resolved to my knowledge.
