### ISSUE TITLE
Reporting issues in generated DB (UhdmLinter)

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3721]
I noticed that a new UhdmLinter binary/test was introduced recently. I would like to add some additional checks to validate the db and wondering if that is the right place to do it or should I introduce a new step at the end of the surelog process. Checks I would like to include -

* Missing parent - no node in the tree should be unparented
* Restrict certain types to specific parent (like `parameter`, `cont_assign`, `param_assign` and alike should always be parented to the `module_inst`)
* Missing vpiName (if corresponding `actual_group` is null) in `ref_obj` (and its derived types) (Because without a name it can never be bound)
* `actual_group` should be pointing to something in the same tree i.e. non-elaborated node should point to an object in the non-elaborated tree only and similarly a node in elaborated tree should point to the elaborated tree. (This may not be true today for all).
* Unbound reference objects
* Weakly referenced nodes in the graphs (nodes that are pointed to only by vpiParent, vpiInstance, vpiUse, vpiActual, vpiTypespec, etc)

UhdmLinter is currently a stand-alone binary. I would like to make these tests part of the surelog process so they get reported. Or, optionally, run the linter process as part of regression so the errors get reported.

Any suggestions?

**Comment by alaindargelas** [comment]
@hs-apotell, please add those checks in the UHDM/templates/UhdmLinter class. Make them warning, so the compilation does not stop for Yosys plugin.
If you make them part of that class, they will run both in Surelog or in the stand-alone uhdm-lint which I wrote to debug some issues on the uhdm model (Outside Surelog memory space, after reloading UHDM)
