### ISSUE TITLE
Crash during typespec binding

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3753]
### Test
tests/SimpleClass1

### Local Change
FactoryT::Erase in UHDM/BaseClass.h isn't deleting the object so it ends up losing the reference/track to an object it created without deleting it. I added the delete call that results in this crash.

### Issue
`unsupported_typespec` gets deleted but references to it aren't cleared.

### Trace

`ref_var` with `unsupported_typespec` gets created here and registered for late typedef binding.
https://github.com/chipsalliance/Surelog/blob/3ce2f5c97696857e9cee91dd9c0ee97fcd9ce20d/src/DesignCompile/CompileType.cpp#L338-L344

The same `unsupported_typespec` gets set on an `array_typespec` here.
https://github.com/chipsalliance/Surelog/blob/3ce2f5c97696857e9cee91dd9c0ee97fcd9ce20d/src/DesignCompile/CompileStmt.cpp#L1146-L1147

When the late type binding loop runs, it queries the `ref_var` and ends up deleting the instance of `unsupported_typespec`.
https://github.com/chipsalliance/Surelog/blob/3ce2f5c97696857e9cee91dd9c0ee97fcd9ce20d/src/DesignCompile/ElaborationStep.cpp#L328-L329

Further down, when saving the db, it crashes because `array_typespec` is referring to a deleted instance.

Similar issue with deleting `unsupported_typespec` in all the following tests -
- BuildUVMPkg
- Driver
- Google
- IncompTitan
- MiniAmiq
- Scoreboard
- SimpleClass1
- SimpleUVM
- SimpleVMM
- TestBatchMode
- UnitAmiqEth

**Comment by alaindargelas** [comment]
@hs-apotell , can you cut and paste here the actual local change that triggers this issue? Without it, I can't reproduce.

**Comment by alaindargelas** [comment]
@hs-apotell I don't see this crashing anymore

**Comment by alaindargelas** [comment]
I found the problem, there are many dangling pointers to the deleted object, working on it.

**Comment by alaindargelas** [comment]
typespec are fixed.

**Comment by alaindargelas** [comment]
Final fix with #3761

**Comment by alaindargelas** [comment]
@hs-apotell , I'm assuming that Serializer::AllObjects() contains all the UHDM objects made at all times, is that correct?

**Comment by alaindargelas** [comment]
OK thanks. Since it is at the heart of the typespec pointer updating procedure I'm writing, I was not sure. 
I seem to still have a few dangling pointers. Two testcases fail on Windows and MacOS: 
IncompTitan  and Earlgrey_Verilator_01_05_21

valgrind Linux is clean at least on IncompTitan

**Comment by alaindargelas** [comment]
Earlgrey_Verilator_01_05_21 is not fixed.
IncompTitan is still failing on Windows and MacOS.

**Comment by alaindargelas** [comment]
Clang address sanitation does not show any problem on that design either.

I ran:

export CXX=clang++-12
Editing the CMake to add: 
set(MEM_SANITIZER_FLAGS
      " -fsanitize=address -fno-omit-frame-pointer"

cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DSURELOG_WITH_TCMALLOC=Off -S . -B build

I even tried  -fsanitize=memory, but that is unusable as it generates Gigabytes of use of uninitialized memory warnings.

**Comment by alaindargelas** [comment]
My last change "works".
I moved the deletion of pointers just before save.
The only diffs are Windows vs Linux diffs, please update the logs.
