### ISSUE TITLE
Combined parse tree with preprocessor and parser tokens (and rules)

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3770]
I managed to merge the output of the preprocessor and the parser to generate a single parse tree that includes both white space information and the macros. This output can be used for text editing tools like document formatting. The merge of these two tree creates a tree with parser tokens interleaved with preprocessor tokens in place of macros.

However, I am running into some name conflicts. For instance, `celldefine_directive` is used in both preprocessor and the parser grammar but with different meaning. This is true for a lot of tokens and rules. When implementing callback listener it isn't explicit whether the callback should be treated in the preprocessor context or the parser context - basically, it's ambiguous.

To resolve this, I propose that all tokens (and rules) in the preprocessor grammar be prefixed with `PP_` and the ones from parser grammar with `PA_`. This will mostly be a text editing exercise but with a lot of modifications across the code. However, this is all internal to Surelog with no external impact (except if someone is already using the publicly available `AstListener` callback interface).

One alternative solution I could think of is to add flags to `VObject` class to track the origin of each object. Not favored because it increases memory footprint (which can be significant for large designs).

@alaindargelas Any objections before embark for this text editing exercise? Open to any alternative solutions.

For the curious minds - How am I merging the preprocessor and the parser trees.

* This is implemented as a separate mode triggered by command line option
* As part of the preprocessor output, macros are not expanded. Instead they are replaced with `special token` that the parser grammar understands. The `special token` also dictates the root node (index in the VObject array) of the subtree in the preprocessor grammar.
* During the parser phase, the `special tokens` are swapped out for the subtree from the preprocessor output.
* Final output includes all the tokens that parser understands interleaved with tokens that come from the preprocessor output. Callback listener walks this merged tree and that's where the name conflicts become a problem.

**Comment by alaindargelas** [comment]
@hs-apotell , I am completely opposed to this task. You can stop right now, I will not accept this change.
It is virtually impossible to achieve. it has been tried before. 
Also the runtime explosion is unbearable..

**Comment by alaindargelas** [comment]
One of the imperatives of the Preprocessor is to actually output a post-preprocessor file that is human readable that substitute all the directives by legal text a parser with no knowledge of the preprocessor directives can parse.

**Comment by Thomasb81** [comment]
Would this "escape identifier" remain compatible with systemVerilog grammar ?

It is quite common and useful to be able to extract per-processor text for debugging purpose, printing additional information not coming from source code is not welcome.

If you need to trackback the origin of source code in preprocessed intermediate text file the standard propose to use `line (See chapter 22.12)
