### ISSUE TITLE
How does Surelog handle duplicate module names between sources and libraries?

### ISSUE THREAD

**Issue by nmoroze** [chipsalliance/Surelog#3790]
Let's say I have a setup like:

```shell
$  tree 
.
├── lib
│   └── foo.v
└── foo.v
```

where the `foo.v` files contain conflicting module names `foo`. If I invoke Surelog like so:

```shell
$ surelog -parse -y lib foo.v -top foo
```

I notice that Surelog points to the top-level module as being in the file explicitly provided as a source:

```
[NTE:EL0503] /tmp/test/foo.v:1:1: Top level module "work@foo".
```

However, if I look at the elaborated file list, it includes the one in the library instead:

```shell
$ cat slpp_all/file_elab.lst
/tmp/test/slpp_all/lib/work/foo.v
```

I'm curious what sort of guarantees, if any, Surelog is meant to provide in this sort of situation regarding which file it ends up elaborating?

**Comment by alaindargelas** [comment]
No guarantees, the standard actually says the last file parsed wins, but in the case of source files and library files I don't even know what is expected.

**Comment by nmoroze** [comment]
Thank you for the clarification!
