### ISSUE TITLE
Include a formatted text serializer to Surelog

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3818]
A number of intermediate output files are un-formatted text (like sep_lst, file_elab.lst, file_map.lst, and file.lst). It would be nice to have these files be formatted text for ease of reading, writing, maintenance, and sharing.

Here are a few options -
* Json - https://github.com/nlohmann/json.git
* Json & Yml - https://github.com/marzer/tomlplusplus.git

Either of these can be integrated as a third_party submodule or drop in as a monolith header.

@hzeller @alaindargelas

**Comment by alaindargelas** [comment]
I vote for Json - https://github.com/nlohmann/json.git

**Comment by QuantamHD** [comment]
Json is prefered.

**Comment by hzeller** [comment]
I'd also prefer json (the nlohmann library is nice).

yaml is pretty painful to process - it is right the mix between structured and unstructured that it ends up more work than just grepping through plain-text (feels like the early 2000's again with the craze to make everything with half-structured XML).

**Comment by alaindargelas** [comment]
Note, @gadfort will need to modify his code when this project is done, he is parsing those files.

**Comment by hzeller** [comment]
we should use the header, but add it to third_party/, not drop somewhere in the project.

**Comment by gadfort** [comment]
Json would be preferred, it's easy to parse. Thanks for looping me in.

**Comment by alaindargelas** [comment]
Let's bring the submodule in third_party
