### ISSUE TITLE
Cleanup: test-logs are written to third_party/$TEST/...

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/Surelog#382]
When running the regression, the resulting logs seem to end up in `third_party/tests/$TEST/...`. This of course is not unnoticed by git, so a git status shows a ton of non-added new files added.

To reproduce:
```bash
make
make regression
git status   # observe all the files
```

Build or test artifacts should never clutter the rest of the code-base (we should regard them as read-only in fact), so we should move them to some output directory in `build/`. Probably as simple as changing a path somewhere.
Good first issue.

**Comment by alaindargelas** [comment]
Has to do with the way the batch scripts are generated for the tests that require to be run in batch mode, Google, Yosys...
The batch scripts are generated by this meta script: tests/create_batch_script.tcl, ran manually in the directory of the test, and the resulting batch script is checked in. Options can be added in the meta script to not generate the logs and slpp_ dirs.
