### ISSUE TITLE
Potential typo in binding logic

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3823]
Potential typo in binding logic.

https://github.com/chipsalliance/UHDM/blob/cc1014efefe245d40600edc837ab3a77905aaeb4/templates/ElaboratorListener.cpp#L302

`netMap.emplace(gsa->VpiName(), gs);` should be `netMap.emplace(gs->VpiName(), gs);`

With the logic in place, only the last `gen_scope` will be in the container.

Similarly here -
https://github.com/chipsalliance/UHDM/blob/cc1014efefe245d40600edc837ab3a77905aaeb4/templates/ElaboratorListener.cpp#L701
https://github.com/chipsalliance/UHDM/blob/cc1014efefe245d40600edc837ab3a77905aaeb4/templates/ElaboratorListener.cpp#L1246

I tried fixing these but it affects the following test cases unexpectedly, generating binding issues.

- ComplexHierPath
- GenModHierPath
- GenScopeFunc
- GenScopeHierPath2
- GenerateBlock
- GenerateRegion
- HierPathBeginBlock
- HierPathInterfBlock
- HierPathTfArg
- ImplicitGenBlock

**Comment by alaindargelas** [comment]
There is only one element in the container at all times.
It is a 1-1 relation in the UHDM implementation.
The standard has a vector but we don't use that.
