### ISSUE TITLE
configure looks for googlest when -DSURELOG_BUILD_TESTS=OFF and -DSURELOG_USE_HOST_GTEST=ON

### ISSUE THREAD

**Issue by yurivict** [chipsalliance/Surelog#3826]
When tests aren't built configure shouldn't look for googletest.

Version: 1.74

**Comment by hzeller** [comment]
oh, yeah, that is not needed in that case :) Can you send a PR to fix ?

**Comment by yurivict** [comment]
Sorry, I am snowed in at the moment.
