### ISSUE TITLE
fatal: Needed a single revision, Unable to find current origin/v1.74 revision in submodule path 'third_party/UHDM'

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/Surelog#3855]
systemverilog-plugin/third_party/surelog$ git submodule update --remote --merge
fatal: Needed a single revision
Unable to find current origin/v1.74 revision in submodule path 'third_party/UHDM'

**Comment by alaindargelas** [comment]
@timkpaine any idea?

**Comment by timkpaine** [comment]
I’m trying to repro locally but theres a lot going on in “systemverilog-plugin” which is now “synlig” (??) and has also changed default branch from master to main.

**Comment by alaindargelas** [comment]
Actually I got the same error doing a recursive update in Surelog
