### ISSUE TITLE
ExprEval returning io_del when returnTypespec is true

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3862]
Code not respecting the input parameter -

https://github.com/chipsalliance/UHDM/blob/165deb9e9ffdc7557d9ce747f9b84353fbb9e6e3/templates/ExprEval.cpp#L2171-L2173

Input parameter `returnTypespec` is ignored.

**Comment by alaindargelas** [comment]
Correct, please submit a fix that return nullptr in the case of returnTypespec == true

**Comment by alaindargelas** [comment]
Yes actually. It is not an error condition. Without a testcase, it's hard to guess. My guess is you'll see no change in the regression results. But I could be wrong.
