### ISSUE TITLE
Potentially wrong typespec binding in ExprEval::evalFunc

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3863]
In this context -
https://github.com/chipsalliance/UHDM/blob/165deb9e9ffdc7557d9ce747f9b84353fbb9e6e3/templates/ExprEval.cpp#L4945-L4951

On line https://github.com/chipsalliance/UHDM/blob/165deb9e9ffdc7557d9ce747f9b84353fbb9e6e3/templates/ExprEval.cpp#L4947
_ioname_ is bound to a new `logic_typespec`. This instance however is never set on the `io` pointer itself.

Later down on line https://github.com/chipsalliance/UHDM/blob/165deb9e9ffdc7557d9ce747f9b84353fbb9e6e3/templates/ExprEval.cpp#L4951
`io->Typespec()` is used which is going to nullptr.

Is this expected behavior? Should the newly instantiated `logic_typespec` be set on the _io_ instance??

**Comment by alaindargelas** [comment]
Correct, please submit a fix.
