### ISSUE TITLE
Proposal: Replace uhdm-dump with uhdm-lint for regression runs

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3870]
Regression runs includes both surelog and uhdm-dump. The latter is currently very time consuming. Some of the larger tests like Earlgrey spin for a long time to dump the uhdm tree as text (files larges than over 1 GB that are unusable). For smaller tests, we already printout the uhdm tree in the test log itself.

Swap out uhdm-dump for uhdm-lint so we can report some of the errors that aren't reported by Surelog itself.

Thoughts?

**Comment by alaindargelas** [comment]
Sounds good.

**Comment by alaindargelas** [comment]
@hs-apotell, BTW, "roundtrip" is now the slow part, can it be sped-up?
