### ISSUE TITLE
Fix Windows CI build

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3873]
@timkpaine @gadfort As per the workflow file history, you guys modified the file in recent past. Does anything stand out that might help fix this issue?

Windows clang target is broken for a few days. Quick glance didn't reveal anything to help fix the issue. Any clues?

**Comment by gadfort** [comment]
@hs-apotell I don't see anything obvious that would cause an issue. I wonder if there were any changes to the windows-2022 image recently

**Comment by timkpaine** [comment]
indeed: https://github.com/actions/runner-images/issues/8343
