### ISSUE TITLE
Unit tests: we need them :)

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/Surelog#52]
There are only end-to-end tests in the system, but no unit tests. This makes it hard to test single classes and check behavior and isolate bugs and impossible to refactor.

We absolutely need to start writing unit-tests. I suggest starting that for each new regression where the class in question has been identified: write a unit-test for such file.

A good, industry proven and widely used unit-test framework is
https://github.com/google/googletest

**Comment by alaindargelas** [comment]
This is ongoing
